src/UI/Nuevo.Web/Models/ErrorViewModel.cs
using System;

namespace Nuevo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/UI/Nuevo.Web/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nuevo.Web
{
    public class Login
    {
        public string Email { get; set; }
    }
}

src/UI/Nuevo.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nuevo.Middlewares.AppHealthManager.Provider.LogicContracts;
using Nuevo.Web.Extensions;

namespace Nuevo.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAppHealthLogic _appHealthLogic;

        public AccountController(IAppHealthLogic appHealthLogic)
        {
            this._appHealthLogic = appHealthLogic;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Login model)
        {
            if (model == null || model.Email.Length < 5) return View();

            var user = _appHealthLogic.GetAccount(model.Email);
            if (user.Status == Core.Infrastructure.ResultType.Error) return View();
            HttpContext.Session.SetAuth(new Auth.AuthModel {Email = user.Data.Email, Key = user.Data.Id});
            return Redirect("/Application");
        }


        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return Redirect("/");
        }
    }
}

src/UI/Nuevo.Web/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nuevo.Middlewares.AppHealthControl.Models.ResponseModel;
using Nuevo.Middlewares.AppHealthControl.Provider.LogicContracts;
using Nuevo.Middlewares.AppHealthManager.Models;
using Nuevo.Middlewares.AppHealthManager.Provider.LogicContracts;
using Nuevo.Web.Extensions;
using Nuevo.Web.QuartzManager;

namespace Nuevo.Web.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IAppHealthLogic _appHealthLogic;
        private readonly IAppHealtControlLogic _abAppHealtControlLogic;

        public ApplicationController(IAppHealthLogic appHealthLogic, IAppHealtControlLogic abAppHealtControlLogic)
        {
            _appHealthLogic = appHealthLogic;
            _abAppHealtControlLogic = abAppHealtControlLogic;
        }


        public IActionResult Index()
        {
            ViewBag.userName = HttpContext.Session.GetAuth().Email;
            var accountKey = HttpContext.Session.GetAuth().Key;
            var model = _appHealthLogic.GetApplication(accountKey);
            return View(model);
        }

        public IActionResult ApplicationTracingList(int appKey)
        {
            var model = _abAppHealtControlLogic.TracingHistory(appKey);
            return View(model);
        }


        public void Add(AppResponsetModel model)
        {
            model.AccountId = HttpContext.Session.GetAuth().Key;

            if (model.Id > 0)
                _appHealthLogic.ApplicationUpdate(model);
            else
                _appHealthLogic.ApplicationAdd(model);
        }

        public void Delete(int id)
        {
            var result = _appHealthLogic.ApplicationDelete(id);
        }

    }
}

src/UI/Nuevo.Web/Views/Application/ApplicationTracingList.cshtml
@model Nuevo.Core.Infrastructure.Result<List<Nuevo.Middlewares.AppHealthControl.Models.RequestModel.TracingRequestModel>>
@{
    Layout = null;

    ViewData["Title"] = "ApplicationTracingList";
}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Tracking Date</th>
            <th scope="col">Status</th>
            <th scope="col">Message</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Data != null)
        {
            foreach (var data in Model.Data)
            {

                <tr>
                    <th scope="row">@(Model.Data.IndexOf(data))</th>
                    <td>@data.CreateDate</td>
                    <td>@data.Status</td>
                    <td>@data.Message</td>
                </tr>
            }
            if (Model.Data.Count == 0)
            {
                {
                    <h2 style="text-align: center">
                        No tracking Records Found
                    </h2>
                }
            }

        }
        else
        {
            <h2 style="text-align: center">
                No tracking Records Found
            </h2>
        }

    </tbody>
</table>

src/UI/Nuevo.Web/Views/Application/Index.cshtml
@model Nuevo.Core.Infrastructure.Result<List<Nuevo.Middlewares.AppHealthManager.Models.AppResponsetModel>>
@{
    ViewData["Title"] = "Index";
}

<script type="text/javascript">
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();
	var actions = $("table td:last-child").html();
	// Append table with add row form on add new button click
    $(".add-new").click(function(){
		$(this).attr("disabled", "disabled");
		var index = $("table tbody tr:last-child").index();
        var row = '<tr>' +
            '<td>#</td>' +
            '<td><input type="text" class="form-control" name="name" id="name"></td>' +
            '<td><input type="text" class="form-control" name="url" id="url"></td>' +
            '<td><input type="text" class="form-control" name="url" id="/*tracking*/"></td>' +
			'<td>' + actions + '</td>' +
        '</tr>';
    	$("table").append(row);
		$("table tbody tr").eq(index + 1).find(".add, .edit").toggle();
        $('[data-toggle="tooltip"]').tooltip();
    });
	// Add row on add button click
	$(document).on("click", ".add", function(){
		var empty = false;
        var input = $(this).parents("tr").find('input[type="text"]');
        console.log(input);
        input.each(function(){
			if(!$(this).val()){
				$(this).addClass("error");
				empty = true;
			} else{
                $(this).removeClass("error");
            }
		});
		$(this).parents("tr").find(".error").first().focus();
        if (!empty) {
            var _name = "";
            var _url = "";
            var _index = 0;
            var _key = "";
            var _tracking = "";
            $(this).parents("tr").find("th").each(function () {
                _key = $(this).text();
            });


            input.each(function () {
                _index++;
                console.log($(this).val());
                $(this).parent("td").html($(this).val());

                switch (_index) {
                case 1:
                    _name = $(this).val();
                        break;
                    case  2:
                        _url = $(this).val();
                        break;
                case 3:
                        _tracking = $(this).val();
                        break;
                default:
                }
			});
			$(this).parents("tr").find(".add, .edit").toggle();
            $(".add-new").removeAttr("disabled");


            $.ajax({
                url: '@Url.Action("Add","Application")',
                type: 'POST',
                dataType: 'json',
                data: { Name: _name, Url: _url,Id:_key,Tracking:_tracking },
                success: function (sc) {

                },
                error: function (err) {

                }
            });
        }

    });
	// Edit row on edit button click

	$(document).on("click", ".edit", function(){

        var _key = "";
        var _name = "";
        var _url = "";
        var _index = 0;

          $(this).parents("tr").find("th").each(function () {
              _key = $(this).text();
          });

        console.log(_key);
        $(this).parents("tr").find("td:not(:last-child)").each(function () {
            $(this).html('<input type="text" class="form-control" value="' + $(this).text() + '">');
            _index++;
            switch (_index) {
            case 1:
                _name = $(this).val();
                break;
            case  2:
                _url = $(this).val();
                break;
            default:
            }
        });
		$(this).parents("tr").find(".add, .edit").toggle();
		$(".add-new").attr("disabled", "disabled");
    });

	// Delete row on delete button click

    $(document).on("click", ".delete", function () {
        var input = $(this).parents("tr");
        var _deleteKey = (input.find('th[scope="row"]')[0]).innerHTML;
        console.log(input);
        console.log(_deleteKey);

        $.ajax({
            url: '@Url.Action("Delete","Application")',
            type: 'POST',
            dataType: 'json',
            data: { id:_deleteKey },
            success: function (sc) {

            },
            error: function (err) {

            }
        });


        $(this).parents("tr").remove();
        $(".add-new").removeAttr("disabled");
    });
});


    function detailApp(id) {

        
        $.ajax({
            url: '@Url.Action("ApplicationTracingList","Application")',
            type: 'POST',
            dataType: 'html',
            data: { appKey:id},
            success: function (result) {
                $("#appHistoryBody").html(result);
            },
            error: function (err) {

            }
        });

}
</script>

<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-8"><h2> Application List</h2></div>
                <div class="col-sm-4">
                    <button type="button" class="btn btn-info add-new"><i class="fa fa-plus"></i> Add New</button>
                </div>
            </div>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th style="width: 83px;">#</th>
                <th>Name</th>
                <th>Application URL</th>
                <th>Tracking</th>
                <th style="width: 133px;">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var data in Model.Data)
            {
                <tr>
                    <th scope="row" style="width: 75px">@data.Id</th>
                    <td>@data.Name</td>
                    <td>@data.Url</td>
                    <td>@data.Tracking</td>
                    <td>
                        <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                        <a class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                        <a class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        <a class="detail" title="Detail" onclick="detailApp('@data.Id')" data-toggle="modal" data-target="#exampleModal"><i class="material-icons">&#xE03B;</i></a>
                    </td>
                </tr>
            }

            </tbody>
        </table>
    </div>
    <h5>Tracing Time Settings => <a href="https://www.freeformatter.com/cron-expression-generator-quartz.html">https://www.freeformatter.com/cron-expression-generator-quartz.html</a></h5>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aplication Tracking History</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="appHistoryBody">
                <h2 style="text-align: center; margin:25px ">
                    LOADİNG...
                </h2>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

src/UI/Nuevo.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css">
        body {
            color: #404E67;
            background: #F5F7FA;
            font-family: 'Open Sans', sans-serif;
        }

        .table-wrapper {
            width: 900px;
            margin: 30px auto;
            background: #fff;
            padding: 20px;
            box-shadow: 0 1px 1px rgba(0,0,0,.05);
        }

        .table-title {
            padding-bottom: 10px;
            margin: 0 0 10px;
        }

        .table-title h2 {
            margin: 6px 0 0;
            font-size: 22px;
        }

        .table-title .add-new {
            float: right;
            height: 30px;
            font-weight: bold;
            font-size: 12px;
            text-shadow: none;
            min-width: 100px;
            border-radius: 50px;
            line-height: 13px;
        }

        .table-title .add-new i {
            margin-right: 4px;
        }

        table.table {
            table-layout: fixed;
        }

        table.table tr th, table.table tr td {
            border-color: #e9e9e9;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table th:last-child {
            width: 100px;
        }

        table.table td a {
            cursor: pointer;
            display: inline-block;
            margin: 0 5px;
            min-width: 24px;
        }

        table.table td a.add {
            color: #27C46B;
        } table.table td a.detail {
            color:rgb(0, 221, 255);
        }

        table.table td a.edit {
            color: #FFC107;
        }

        table.table td a.delete {
            color: #E34724;
        }

        table.table td i {
            font-size: 19px;
        }

        table.table td a.add i {
            font-size: 24px;
            margin-right: -1px;
            position: relative;
            top: 3px;
        }

        table.table .form-control {
            height: 32px;
            line-height: 32px;
            box-shadow: none;
            border-radius: 2px;
        }

        table.table .form-control.error {
            border-color: #f50000;
        }

        table.table td .add {
            display: none;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nuevo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
              @{
                  string user = ViewBag.userName;
                  if (string.IsNullOrEmpty(user))
                  {
                      
                  }
                  else
                  {
                      <div class="row" style="width: 100%">
                          <div class="col-md-6" style="text-align: left">
                                            <h4> Welcome  <b>@user</b> </h4>
                          </div>
                          <div class="col-md-6" style="text-align:right">
                                  <a class="btn btn-info" href="@Url.Action("LogOut", "Account")">LogOut</a>

                          </div>
                        
                      </div>
                  }
              }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Aplication Control - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>